### ISSUE TITLE
Access denied when running modt_status.py

### ISSUE THREAD

**Issue by aleitner** [Xaero252/Mod-T-Scripts#1]
I run the command with both `sudo` access and regular user, but I am getting the same error back. Not sure why.

Mac OSX 10.13.2
Python 3.6.4
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)
pyusb 1.0.2
dfu-util 0.9
curl 7.54.0

Mod-T Firmware 0.15

Script:
```
python3 modt_status.py
```
```
sudo python3 modt_status.py
```

Return:
```
Traceback (most recent call last):
  File "modt_status.py", line 30, in <module>
    dev.write(4, '{"metadata":{"version":1,"type":"status"}}')
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 940, in write
    intf, ep = self._ctx.setup_request(self, endpoint)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 216, in setup_request
    self.managed_claim_interface(device, intf)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/usb/core.py", line 167, in managed_claim_interface
    self.backend.claim_interface(self.handle, i)
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 811, in claim_interface
    _check(self.lib.libusb_claim_interface(dev_handle.handle, intf))
  File "/usr/local/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
```

**Comment by Xaero252** [comment]
Sorry for the delay in getting back to you on this.
I don't have a lot of experience working with OSX; but from what I read, libUSB and OSX don't really cooperate. You can probably use this as a workaround:
Run kextstat before plugging the mod-t in
Plug the mod-t in and then run kextstat again.
Look for a NEW driver being loaded.
Once you have identified the driver being loaded:
sudo kextunload -b com.apple.driver.thedrivername

Afterwards the Mod-T scripts should function. I'll have to look into possibly using hidapi in the long run to provide OSX support. If this does work, could you please post the name of the driver that it loads for the Mod-T?

Also, do note, the firmware update scripts aren't currently setup to work correctly. One script will only put the Mod-T into DFU (firmware update) mode and the other will only send the firmware to the Mod-T. Hopefully I can get some free time and motivation to line up so I can polish these a little more soon.
